### ISSUE TITLE
Make the column width adjustable by the user as in LineUp

### ISSUE THREAD

**Issue by mijar** [Caleydo/taggle#106]
Grid layout with fixed width - if we want the column to grow/ shrink in size, the rest of the columns shrinks/grows equally. The handle is grabbed and moved as in LineUp, but the behavior of the rest of the layout should be as follows:
![img_0783](https://cloud.githubusercontent.com/assets/7511570/23065198/9fba0c34-f514-11e6-82b0-6b59f42f801d.JPG)

**Comment by thinkh** [comment]
General question: Do we need this feature for the demo in the paper? If we don't show it, it might be better to postpone it.

**Comment by mstreit** [comment]
Yes, I think we need it because resize action will trigger automatic aggregations.

**Comment by sgratzl** [comment]
I vote to include this in the demo. Not as a feature but with the narrower column width you can't see most of the values because they are truncated.

**Comment by sgratzl** [comment]
also encode the width in the url for simpler sharing
