### ISSUE TITLE
aggregate all groups by default?

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/taggle#122]
when the user stratifies by a column, should we aggregate all groups by default?

see also #88

**Comment by mstreit** [comment]
aggregating the groups by default solves the immediate scalability issue. however, as mentioned by @zichner, it does not solve the problem that a user wants to see an initial overview before stratifying the table.

**Comment by sgratzl** [comment]
Issue moved to [Caleydo/lineupjs #415](https://github.com/Caleydo/lineupjs/issues/415) via [**ZenHub**](https://www.zenhub.com/)
