### ISSUE TITLE
Replace data type icons in select2 and side panel

### ISSUE THREAD

**Issue by thinkh** [Caleydo/taggle#133]
Coming from https://github.com/Caleydo/mothertable/issues/349 @alexsb wrote:

I find the data type icons a little confusing, especially the numerical icon looks like the sorting icon. 

I'd instead go for something like this: 

![image](https://cloud.githubusercontent.com/assets/2039375/25363818/e34e43cc-291a-11e7-81d9-8fc9aa6e5c51.png)

Or this: 

![image](https://cloud.githubusercontent.com/assets/2039375/25363845/1be80d1c-291b-11e7-8733-a278dddbf902.png)

We need icons for: 

Labels / text - probably "T"
Numerical - probably "#"
Categorical - probably the three dots show above
Nominal (string) - probably the three numbers shown above

---

The first set is from Kitware's Resonant: https://resonantlab.kitware.com/

Probably custom made, but I'm sure it's open source. 

The second is tableau.

**Comment by mstreit** [comment]
already done in the latest prototype
![image](https://user-images.githubusercontent.com/4129755/32604952-d59150b8-c54f-11e7-90bc-7f781baee695.png)
