### ISSUE TITLE
Add other sample datasets. 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/taggle#135]
We only have the AIDS dataset, we should provide a list of several datasets to show that the tool is general.

**Comment by mstreit** [comment]
@sgratzl, what's the status here? I've seen that you are able to switch between datasets locally.

**Comment by mstreit** [comment]
done with #134. the user can upload CSV data and also switch between preloaded datasets. 
see taggle-daily.caleydoapp.org. for TCGA data will will deploy an Ordino that uses Taggle instead of LineUp.
