### ISSUE TITLE
Replace red-green color map with red-blue colormap

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/taggle#137]
@alexsb commented on [Tue Oct 17 2017](https://github.com/Caleydo/lineupjs/issues/385)

We use a red-green colormap for ordinal data: 
![image](https://user-images.githubusercontent.com/2039375/31678160-7c05d0f0-b32a-11e7-9413-f9bb252dee0e.png)

There is no good reason to use this color map. It opens us up to criticism as it's problematic for red-green colorblind users. Replace with red-blue colormap.

**Comment by mijar** [comment]
#ca0020 Low human dev
#f4a582 Medium
#92c5de High
#0571b0 Very high
