### ISSUE TITLE
Sort consistency after removing column ?

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/taggle#140]
Use case:
Add columns Origin, Career Status and Gender.
The sorted index are for example : [0,9,11,8,6,1,2,3,10] in asc order
Now remove Origin.
Should we update the table view with new sort hierarchy as (Career Status > Gender)  or keep the currently sorted index.

**Comment by mstreit** [comment]
The sorting should be updated to reflect the sorting hierarchy as shown in the filter view.

**Comment by bikramkawan** [comment]
![2017-05-23_12-57-34](https://cloud.githubusercontent.com/assets/12292333/26351336/8c2a7c9c-3fb7-11e7-8d4b-afbe757f2315.gif)
