### ISSUE TITLE
Attention sign instead of yellow halo in overview checkbox

### ISSUE THREAD

**Issue by katush** [Caleydo/taggle#143]
The yellow halo around overview checkbox, when the overview mode doesn't fit on screen is not very informative.
Replace it with atention/warning sign.
![image](https://user-images.githubusercontent.com/8986080/31950278-897a2cde-b8db-11e7-9481-563bb3e4f879.png)

**Comment by mstreit** [comment]
replace green halo with nothing (everything is fine)
replace yellow halo with this icon: http://fontawesome.io/icon/exclamation-triangle/

**Comment by sgratzl** [comment]
Issue moved to [Caleydo/lineupjs #413](https://github.com/Caleydo/lineupjs/issues/413) via [**ZenHub**](https://www.zenhub.com/)
