### ISSUE TITLE
ToolTip on hover in the table view in the whole area of the bar

### ISSUE THREAD

**Issue by mijar** [Caleydo/taggle#144]
Currently the Tooltip appears only when hovering over the actual colored rectangle in histogram:

![01tag](https://user-images.githubusercontent.com/7511570/31951180-ab307f20-b8dd-11e7-880d-899f5114bc64.jpg)

I would expect the ToolTip to appear even in the area that is dedicated to the bar, like here in the sketch below. It is highly useful to get the data when the bar is so small you cannot even see it...

![02tag](https://user-images.githubusercontent.com/7511570/31951280-ef997bf8-b8dd-11e7-8cb7-1e5654063107.jpg)

**Comment by mstreit** [comment]
moved to https://github.com/Caleydo/lineupjs/issues/408
