### ISSUE TITLE
Create anonymous public demo

### ISSUE THREAD

**Issue by thinkh** [Caleydo/taggle#145]
Since the paper reviews are double-blind our demo must be anonymous, too.

@sgratzl Could you please configure the nginx on AWS that we can use the Public IP of our cluster. The result would be something like `http://01.23.456.789/taggle`.

**Comment by mstreit** [comment]
I think @anita-steiner could also take a look at this issue.

**Comment by sgratzl** [comment]
actually, one just need to add the port of the taggle app to the security group such that it can be accessed externally and then you can use: http://cluster-ip:xxxx Tho, if we are not going to change all caleydo related things, I don't see the points. Even tho it is Caledyo, it is not directly related to a specific person

**Comment by sgratzl** [comment]
-> [Link](http://52.57.234.254:32793/)
