### ISSUE TITLE
Filterboxes dont work correctly

### ISSUE THREAD

**Issue by NMO13** [Caleydo/taggle#146]
Create two numerical columns. Stack them. Go to "edit weights". Change the weights.

Expected: The weights should change independently.

Actual: Changing one weight also changes all other weights.

![20171213_195934](https://user-images.githubusercontent.com/3988444/33992603-93d0cd1c-e0d3-11e7-835d-e786413a8c00.gif)

**Comment by sgratzl** [comment]
Issue moved to [Caleydo/lineupjs #499](https://github.com/Caleydo/lineupjs/issues/499) via [**ZenHub**](https://www.zenhub.com/)
