### ISSUE TITLE
Show selection of rows without hiding content

### ISSUE THREAD

**Issue by mstreit** [Caleydo/taggle#174]
At the moment the whole row will get filled with the selection color. However, this hides the actual content (color of category, labels (if present), bars, etc.

![image](https://cloud.githubusercontent.com/assets/4129755/23606013/3cc3c810-025f-11e7-839c-326f93ffc485.png)

**Comment by thinkh** [comment]
We could use the stroke property instead of fill. However, we can only apply this to single cells and not for the whole row (similar to LineUp), due to the different columns and multiforms.

**Comment by mstreit** [comment]
Yes, if the row is high enough we can use stroke instead of fill.

**Comment by mstreit** [comment]
As we have the brushing now, we could also just make the brushed rows higher. In the aggregated vis, we can still highlight the brushed elements using color.

http://www.bytemuse.com/datacomb/demo/

**Comment by mstreit** [comment]
@alexsb, what do you think?

**Comment by alexsb** [comment]
I think a proper implementation that draws a frame is desirable. I don't think this is critical though. 

Re changing row-height - maybe :) this is tricky if you're trying to be space filling.

**Comment by mstreit** [comment]
We already make brushed rows higher, except if there is enough space to show all of them in a height that allows reading labels - then we just leave it as it is.

**Comment by mstreit** [comment]
But yes, in the case where the brushed rows have the same size as other rows, there needs to be some kind of highlight anyway. So let's draw a frame. @thinkh, can you please change the style accordingly?

**Comment by sgratzl** [comment]
see https://github.com/phovea/phovea_vis/pull/62
