### ISSUE TITLE
support stratifications

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/taggle#199]
in the current version only vectors and matrices are supported. However, in the TCGA case most of the categorical data are stored in stratifications. 

a stratification can be converted into a categorical vector

**Comment by mstreit** [comment]
Yes, this is very important for the TCGA use case.

**Comment by mstreit** [comment]
The heatmap clusterings from Firehose for TCGA data works. 
![image](https://cloud.githubusercontent.com/assets/4129755/24251605/fb519db0-0fda-11e7-86dd-63a233632d86.png)

@sgratzl, can you please file a PR? I will merge it then.

**Comment by mstreit** [comment]
The next and last step to address this issue would be to also let the user specify specific columns from categorical matrices (e.g., add the mutation status for a specific gene as categorical columns). This is important to finally be able to re-create the TCGA figures from publications.

The functionality is already used in StratomeX (http://stratomex.caleydoapp.org) where the user can access it via the LineUp based interface at the bottom. We should discuss in the evening how we want to handle this in the Taggle interface.

**Comment by sgratzl** [comment]
https://github.com/Caleydo/mothertable/tree/sgratzl/stratification adds all the columns of a matrix a column vectors. So, at the moment you end up with around 20k entries in the options menu

**Comment by mstreit** [comment]
Nice! The interface for this is part of #266.

**Comment by mstreit** [comment]
https://github.com/Caleydo/mothertable/tree/sgratzl/stratification can be merged as soon as #266 is implemented.

**Comment by thinkh** [comment]
I tried this after implementing the select2. Unfortunately, the performance is soooo bad. The Select2 has serious performance issues, when I add the whole 20k entries as array, because in the background it creates still a HTML select element (and the amount of DOM elements slows it down). So the only solution I see is to use the AJAX feature, which requires a backend for that call. 😐

**Comment by mstreit** [comment]
OK. I suggest to filter the list down to only include a gene subset, which we need for the use case section.

**Comment by thinkh** [comment]
Ok, sounds reasonable. @mstreit Can you please define the the subset, so that @sgratzl could apply the subset?

**Comment by mstreit** [comment]
For this we need to think about what we want to show in the use case.

**Comment by sgratzl** [comment]
> So the only solution I see is to use the AJAX feature, which requires a backend for that call.

you could fake the ajax call by providing a different transport method:

https://select2.github.io/options.html#can-an-ajax-plugin-other-than-jqueryajax-be-used

**Comment by sgratzl** [comment]
fake ajax
```
ajax: {
        cache: false,
        dataType: 'json',
        delay: 0, // increase for 'real' ajax calls

        data: (params) => {
          return params; // params.term = search term
        },

        // fake ajax call with local data
        transport: (queryParams, success, error) => {
          return success({
            items: filterData(data.slice(0), queryParams.data.term)
          });
        },

        // parse the results into the format expected by Select2.
        processResults: (data, params) => {
          return {
            results: data.items,
            pagination: {
              more: false
            }
          };
        }
      }
```
