### ISSUE TITLE
Horizontal matrix aggregation

### ISSUE THREAD

**Issue by mstreit** [Caleydo/taggle#215]
It should be possible to aggregate single rows of a matrix to a single number (min, max, avg, median, etc.).

**Comment by bikramkawan** [comment]
![apr-05-2017 1-10-21 pm](https://cloud.githubusercontent.com/assets/12292333/24702956/643acd8a-1a01-11e7-897c-b4f15de484b7.gif)

**Comment by bikramkawan** [comment]
I will replace that with same as in lineup as in sketch
![a392f3c6-d362-11e6-8a5d-c633e7315532](https://cloud.githubusercontent.com/assets/12292333/24703049/ca2189c2-1a01-11e7-9054-bc73ce29f8ed.gif)

**Comment by mstreit** [comment]
Can I test this state? In which branch do I see it? There is no link to any commit.

**Comment by bikramkawan** [comment]
You can switch to branch matrix. Sorry, I forgot to link the commit to this issue.

**Comment by mstreit** [comment]
OK. So after flattening the matrx it behaves like a regular single value numerical column, right (with all the vis options etc.)?

**Comment by bikramkawan** [comment]
Current State: Sketch Below:
Points of discussion:

- Should the other stratifiers and the support view of matrices be removed or keep as it is ?

- If the matrix is converted to vector. Currently, it is stacked at the bottom of the filter list which also takes part in sorting.It is just the normal numerical column similar to other. It will be part of filter operation and sorting by changing its position which will also reflect on the table view. 

- If the vector is converted to matrix it is stacked at the bottom of the filter list and remove from sort hierarchy. This situation will be same as before we switch back to vector.


![2017-04-06_13-42-05](https://cloud.githubusercontent.com/assets/12292333/24752633/1ab0975c-1acf-11e7-8f1f-11e448bdce4a.gif)

**Comment by mijar** [comment]
ad1: I think it should behave the same as in the case of rows. In other words - if you have a matrix stratified by continent, I would expect that after custom aggregation, it would end up with 3 columns of (average / etc.) values per each continent.

ad2&3: looks nice and quite easy to follow in my opinion, great job @bikramkawan

**Comment by bikramkawan** [comment]
Strategy:
CM = Column Manager

**Matrix to Vector Conversion:**

- Stratify  columns then choosing aggregate function and trigger  to the CM -> App

- Convert Matrix Views in vector(V1, V2...) with aggregate function

- Create independent columns and filters accordingly for each vector(V1, V2...) 

- Add all the column stratifiers of the original matrix as a flag to V1, V2...

- update main view and support view

**Vector to Matrix Conversion**

- Choose conversion icon and trigger to the CM -> App

- Get matrix data from Number Columns i.e. V1, V2...

- Create independent Matrix Columns (M1, M2...) and filters accordingly for each vector(V1, V2...) 

- Initially, there will be no column st ratifiers i.e. empty columns in support view of the newly created matrix.

- Add all the column stratifiers of the original matrix as a flag to M1, M2...

- Trigger SupportView to restore the previous column stratifiers on the top of matrix

- update main view and support view


![2017-04-12_16-53-40](https://cloud.githubusercontent.com/assets/12292333/24964755/6a144136-1fa2-11e7-8c93-01e531da1310.gif)

**Comment by mijar** [comment]
I am not sure if splitting it into threee different columns in this manner makes sense...I would vote more for something like this:
https://docs.google.com/presentation/d/1I7y-VKfG02UyAIlYT_ZsklegRdiLz4rrrX5WiqO-hP0/edit#slide=id.g1b9192e035_0_103   (slides 39 up)

**Comment by mstreit** [comment]
Works in principle. New issues will be filed for buggy behavior.
