### ISSUE TITLE
No labels in mosaic plot

### ISSUE THREAD

**Issue by thinkh** [Caleydo/taggle#230]
Coming from PR #228.

### Steps to reproduce

1. Add a categorical column (e.g., `patients.gender`)

### Observed behavior

Now I still have the error that no labels are shown. The DOM elements exists, but the group has display="none". I assume that one of the categories is too small to show the label and therefore all labels are hidden. The improvement would be that you check for each block/rect individually if the text can be shown. 

![](https://cloud.githubusercontent.com/assets/5851088/23995500/2641fe52-0a4a-11e7-948c-27654b073002.png)

### Expected behavior

The label should be shown if there is enough space for a block.

**Comment by mstreit** [comment]
We decided to not use the mosaic plot implementation. For aggregated groups we just create a new renderer that fills the area with the category color and shows the label.
