### ISSUE TITLE
Fix width of mosaic multiforms

### ISSUE THREAD

**Issue by mstreit** [Caleydo/taggle#239]
There is some white space problem introduced when the width of columns gets reduced.

![image](https://cloud.githubusercontent.com/assets/4129755/24049784/5670543c-0b2d-11e7-9b34-7350138a4b8e.png)

**Comment by mstreit** [comment]
Low prio, as mosaic is not the default vis for categorical attributes anymore.

**Comment by NMO13** [comment]
Mosaic implementation not used anymore.
