### ISSUE TITLE
Update column stratifications when re-ordering the filter

### ISSUE THREAD

**Issue by thinkh** [Caleydo/taggle#253]
Coming from PR #241, re-ordering the filter for a matrix idType is not reflected in the column stratifications.

The sorting of the multiforms itself is working, but the DOM elements of the columns are not updated (see
https://github.com/Caleydo/mothertable/pull/241/files#diff-99a8c04a7d4d1ef691bd9fdae88553f6R122).

**Comment by bikramkawan** [comment]
It seems it might have been fixed from old PR so I am closing here. 
![2017-06-08_13-18-50](https://user-images.githubusercontent.com/12292333/26926224-1e0ae628-4c4d-11e7-95bb-4069546a3132.gif)
