### ISSUE TITLE
Confusing behavior when switching the visualization type

### ISSUE THREAD

**Issue by thinkh** [Caleydo/taggle#258]
Coming from https://github.com/Caleydo/mothertable/pull/257#issuecomment-288371979, which is actually not a bug as I reported in the PR, but a confusing behavior in our concept. I try to briefly explain the problem. 

Again the screencast:
![taggle_wrong-aggregation-vis](https://cloud.githubusercontent.com/assets/5851088/24197540/510dc56e-0f02-11e7-94e2-369750c1b502.gif)

**Reproduction**
* Filter the data to switch automatically to unaggregated vis
* Switch the vis for unaggregated mode for one column

**Explanation**
* All rows are in automatic mode and use unaggregated visualizations, because there is enough space to show heatmaps
* When the user switches to the list visualization (which is a unaggregated vis) it has to less height to show the list view
  * Side note: The minimum height for list is greater than for the bar chart
* Therefore the automatic mode decides to switch to the aggregated visualization and shows a histogram --> this is confusing

**Possible Solutions**
1. We should also show in the automatic mode the currently selected mode in the aggregation switcher
    * this visual feedback would help the user to see that the automatic mode has switched
2. We can also ask the user if he wants enforce the list view and therfore activate scrolling
    * at the moment this can be manually enforced, by switchting to unaggregated mode and then selecting the list vis 

I recommend to first implement option 1 and try it again. If this doesn't minimize the confusion I would suggest to implement option 2.

**Comment by mstreit** [comment]
@alexsb, any idea how to address this?

**Comment by mstreit** [comment]
Won't fix now but I will leave it open as a reference for future discussions.
