### ISSUE TITLE
Remove flickering for relayout actions

### ISSUE THREAD

**Issue by mstreit** [Caleydo/taggle#281]
Every time we calculate the layout, the whole table flickers. Is there a way we can handle this? Maybe delay the rendering until the layout calculation is done? Or other ideas? 

The perfect solution would of course be to have animated transitions explaining the changes. But I know that his will be difficult to achieve with the current implementation (also see #81).

**Comment by mstreit** [comment]
@thinkh, you have the most web dev experience. What do you think?

**Comment by thinkh** [comment]
See PR #337 for more information.

**Comment by mstreit** [comment]
Does not happen anymore because of removed fisheye.
