### ISSUE TITLE
Some non brushed elements get increased although they shouldn't

### ISSUE THREAD

**Issue by mstreit** [Caleydo/taggle#285]
When brushing items quickly, some items will not be selected. However, their height is still increased. The highlight and the height change should be consistent.

![image](https://cloud.githubusercontent.com/assets/4129755/24334106/ac2fb3b6-1264-11e7-8796-4659569bac2c.png)

**Comment by mstreit** [comment]
We can fix this after the deadline though.

**Comment by katush** [comment]
@mstreit  @NMO13 I think you mention Martin is going to work on this?

**Comment by mstreit** [comment]
Fixed by removing fish-eye.
