### ISSUE TITLE
Hatch pattern in one filter affects other filters

### ISSUE THREAD

**Issue by mstreit** [Caleydo/taggle#302]

**Comment by bikramkawan** [comment]
I cannot reproduce @mstreit Can you tell me how to reproduce ?
![2017-03-27_18-07-11](https://cloud.githubusercontent.com/assets/12292333/24366101/5e96277a-1318-11e7-8ecc-ad0804b7432e.gif)

**Comment by mstreit** [comment]
Cannot reproduce either. Will report here when I see it again.
