### ISSUE TITLE
Horizontal column (the other direction) is not removed from table view after clicking the bin icon in side panel

### ISSUE THREAD

**Issue by mijar** [Caleydo/taggle#306]
![image](https://cloud.githubusercontent.com/assets/7511570/24379273/aebf4f5a-1346-11e7-9ece-9d79581d769d.png)
I wanted to remove the upper categories but it stayed there

**Comment by bikramkawan** [comment]
![2017-06-08_15-57-38](https://user-images.githubusercontent.com/12292333/26932264-5467edf4-4c63-11e7-8b9f-edb0b66fbb32.gif)

**Comment by NMO13** [comment]
Works basically, however the URL hash won't be updated properly:
![bug](https://user-images.githubusercontent.com/3988444/26966876-36ad9fcc-4cfc-11e7-8007-e8e58e1ea947.gif)

**Comment by NMO13** [comment]
@bikramkawan If you want, I'll try to fix it.

**Comment by bikramkawan** [comment]
@NMO13 Please feel free.
