### ISSUE TITLE
String column should not draw labels below a certain row height

### ISSUE THREAD

**Issue by mstreit** [Caleydo/taggle#311]
![image](https://cloud.githubusercontent.com/assets/4129755/24401823/328443d0-13b6-11e7-914f-f856f9a1aee0.png)

**Comment by thinkh** [comment]
Thomas suggested in the meeting that we can still show the first few items as strings (in the aggregated mode) and indicate that there are more strings in this group. The first few strings would be helpful for the analyst to know what the group contains.

**Comment by alexsb** [comment]
And then, in the last row, it should read "33 more items [show all]" - and clicking on show-all should de-aggregate the column.
