### ISSUE TITLE
Align the reversed matrix attributes to the bottom

### ISSUE THREAD

**Issue by mijar** [Caleydo/taggle#320]
![image](https://cloud.githubusercontent.com/assets/7511570/24422984/c4ac3cc8-13fb-11e7-8490-5a871c1cdea1.png)

See HAART availability in the figure

**Comment by mstreit** [comment]
Also the alignment of the meta-rows for the right matrix is buggy.

**Comment by bikramkawan** [comment]
![image](https://cloud.githubusercontent.com/assets/12292333/26551290/0fa9fac4-4482-11e7-9d3a-3bd663177884.png)

**Comment by thinkh** [comment]
Works as @bikramkawan posted.
