### ISSUE TITLE
Cannot click on matrix data 

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/taggle#325]
### Steps to reproduce

1.Any  Origin 
2. Add Number one hits
3. Add continent in other direction
4.Filter some data from the continent.
5.Try to click on matrix

### Observed behavior
Cannot click because SVG of taggle axis was foreground.
### Expected behavior
Should be clicked able.

![image](https://cloud.githubusercontent.com/assets/12292333/24443798/5193cada-1464-11e7-9d17-b20be8ef32c8.png)

**Comment by mstreit** [comment]
Works.
