### ISSUE TITLE
deselect selected item

### ISSUE THREAD

**Issue by mijar** [Caleydo/taggle#327]
### Steps to reproduce

1. Select any item(s)
2. Try to delect it to have all items in overview lvl

![image](https://cloud.githubusercontent.com/assets/7511570/24454225/6017a668-148b-11e7-8949-ce8d95498d6d.png)

### Expected behavior
* If I click on a selected element I would expect it to be deselected

**Comment by NMO13** [comment]
Is this still an important feature for the paper release?

**Comment by mstreit** [comment]
No. I've marked this as post-submission.

**Comment by NMO13** [comment]
This is standard behaviour in Excel and other tools and therefore keep it as it is now.
