### ISSUE TITLE
Changing the order of numerical columns in side panel does not have any effect in the table view

### ISSUE THREAD

**Issue by mijar** [Caleydo/taggle#329]
I put there the human dev. index  first with fertility attribute, selected the countries with the most children per woman and then I wanted to see how they stand when I change the order in the side panel for the sorting to be driven by condom use second after the human dev. index...nothing happened

![image](https://cloud.githubusercontent.com/assets/7511570/24454793/7b958732-148d-11e7-9259-e134e4ba810b.png)

**Comment by bikramkawan** [comment]
@mstreit This is should be fixed from recent merge right ?

**Comment by mstreit** [comment]
I did not test the scenario @mijar mentioned. Can you do this please?

**Comment by mstreit** [comment]
Works.
