### ISSUE TITLE
The select2 popup is not user-friendly when having less space

### ISSUE THREAD

**Issue by mijar** [Caleydo/taggle#330]
Sometimes the popup appeared above the textbox, but mostly it stayed as it is in the screenshot. It is then really hard to select something that you don't know is there...maybe a scrollbar in the popup would be enough

![image](https://cloud.githubusercontent.com/assets/7511570/24455789/2987e06c-1491-11e7-9608-cccc52cd7440.png)

**Comment by sgratzl** [comment]
I reduced the default height of the selection box and made the max-height dependent on the availiable screen height. 

re above vs below -> select2 is smart enough if the whole thing fits above but not below it shows it above. However, if the box fits at neither place fully it will go for below.

**Comment by thinkh** [comment]
Thanks @sgratzl. It's working now.
