### ISSUE TITLE
Matrix visualization is buggy

### ISSUE THREAD

**Issue by mijar** [Caleydo/taggle#331]
when aggregated, the placement histograms of matrices is being shifted with every group

![image](https://cloud.githubusercontent.com/assets/7511570/24458599/a5337390-1499-11e7-93aa-7bd2af68c143.png)

**Comment by mstreit** [comment]
Seems to be fixed.
![image](https://cloud.githubusercontent.com/assets/4129755/25610727/a6dfe494-2f24-11e7-8007-9d54b9958c30.png)
