### ISSUE TITLE
attributes in column direction do not reflect the column count in matrix

### ISSUE THREAD

**Issue by mijar** [Caleydo/taggle#332]
There should be only years 2010 - 2015 shown in the above attributes

![image](https://cloud.githubusercontent.com/assets/7511570/24464610/a7f66efa-14aa-11e7-95a8-e55caee25a15.png)

**Comment by bikramkawan** [comment]
![image](https://cloud.githubusercontent.com/assets/12292333/26550571/a19c9d1e-447e-11e7-8bae-8ee68df780a7.png)

**Comment by thinkh** [comment]
Works as @bikramkawan posted.
