### ISSUE TITLE
Add ID/name column by default as first column

### ISSUE THREAD

**Issue by mstreit** [Caleydo/taggle#333]
related to #311

**Comment by alexsb** [comment]
I'd even argue that we should try to add multiple or even all columns by default. In excel, you'd also expect to see all columns.

**Comment by mstreit** [comment]
For small datasets we can do that. But for larger datasets it will get difficult to set the filters in the right panel.

**Comment by alexsb** [comment]
You mean if you have too many columns, or why?

Generally, the panel on the right does introduce a level of indirection which I'm not 100% sure about. But It leaves us with more space for the individual columns.

**Comment by mstreit** [comment]
Yes, the side panel has pros/cons. But as the hierarchical sorting is independent of the order of columns, it cannot be in place. Also filtering would be difficult for narrow columns.

**Comment by mstreit** [comment]
So by default the user will see two columns: rank (#342) and ID.

**Comment by thinkh** [comment]
The ID column is added by default. If there is no ID column available for the IDType an error message is shown in the console (and of course no column is added).
