### ISSUE TITLE
Add main header on top of vectors converted from matrix

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/taggle#340]
The main header will be useful for

- Restoring the whole vectors to matrix back again. 

- Moving the converted vector out of the matrix scope

- It will quickly indicate matrix converted to vectors.

![image](https://cloud.githubusercontent.com/assets/12292333/25119130/45ac5d30-2419-11e7-8773-35835f5c60e6.png)

**Comment by mijar** [comment]
How about the solution shown in sketches? I mentioned it in #215

**Comment by bikramkawan** [comment]
We need to find the way how to handle if we click numerical column of subset below Matrix header. For now I have created the new instance of Matrix.
![2017-04-20_13-25-08](https://cloud.githubusercontent.com/assets/12292333/25229707/a0d3566e-25d1-11e7-845e-7c2e6d149ed7.gif)

**Comment by bikramkawan** [comment]
Fix Row correspondence
![2017-05-30_14-12-34](https://cloud.githubusercontent.com/assets/12292333/26582633/3233fd90-4542-11e7-9747-27b8eb9bf463.gif)
