### ISSUE TITLE
Turn off the magic

### ISSUE THREAD

**Issue by alexsb** [Caleydo/taggle#344]
Magic is usually not a good idea. Here. I've just added a couple of columns and sorted by continent: 

![image](https://cloud.githubusercontent.com/assets/2039375/25363167/cc73c7e4-2915-11e7-997b-d3945a696a5f.png)

I did not ask for this aggregation, and it is confusing. 

Let's never aggregate automatically, it's just confusing.l

**Comment by thinkh** [comment]
Turned off by default with @katush's last PR #351. I close this here.
