### ISSUE TITLE
Give all columns a narrower default width

### ISSUE THREAD

**Issue by alexsb** [Caleydo/taggle#348]
Right now, the columns are pretty wide by default: 

![image](https://cloud.githubusercontent.com/assets/2039375/25363656/831c2eca-2919-11e7-8c63-01a77e031e6c.png)

In addition to being able to resize them manually (#347), I'd start out with a much narrower column. In many cases the first ~10 characters of a field will be sufficient to understand what's going on. 

Also, numerical columns are pretty wide. Compare that to lineage: 

![image](https://cloud.githubusercontent.com/assets/2039375/25363750/3770d06a-291a-11e7-9143-04e8bb8649f3.png)

Numerical columns could be half as wide. The buttons should be accessible through a menu or a right-click on the header.

**Comment by mstreit** [comment]
related to #276

**Comment by thinkh** [comment]
Done by @katush.

![grafik](https://cloud.githubusercontent.com/assets/5851088/26592015/c95ca5a6-455f-11e7-9638-2b8de3f47c2e.png)
