### ISSUE TITLE
Apply column stratification of first categorical column correctly

### ISSUE THREAD

**Issue by thinkh** [Caleydo/taggle#352]
* Release number or git hash: 
* Web browser version and OS: 
* Environment (local or deployed): 

### Steps to reproduce

1. Add a matrix (e.g. Number1Hits)
2. Add a categorical column for this matrix (e.g. continent)
3. Split matrix by min/mean/max (type doesn't matter)

### Observed behavior
* The matrix is not splitted into 3 vectors as expected
* The user first has to click the stratify button of the categorical column and then split

![splitting_matrix](https://cloud.githubusercontent.com/assets/5851088/25608238/6ed5f052-2f1a-11e7-8a20-ba762b1ae272.gif)

### Expected behavior
* The stratification should be applied automatically when adding the first categorical column to a matrix

**Comment by mstreit** [comment]
The TCGA stratification are already available in this branch:
https://github.com/Caleydo/taggle/tree/sgratzl/stratification
However, as every gene can be a stratification we run into a scalability problem for the select2 search.

**Comment by bikramkawan** [comment]
![2017-06-08_11-34-37](https://user-images.githubusercontent.com/12292333/26922210-bf916eea-4c3e-11e7-9703-eedf108ec8eb.gif)
