### ISSUE TITLE
Histogram for matrices in Side panel

### ISSUE THREAD

**Issue by mijar** [Caleydo/taggle#360]
The histogram (or what this should be) for the added matrix of number of people living with aids is somehow confusing...is the implementation correct? Or what is it depicting?

![image](https://cloud.githubusercontent.com/assets/7511570/26203709/95cc6ffa-3bdc-11e7-955e-40376261f145.png)

**Comment by sgratzl** [comment]
it is an histogram of the flatted values given the dataset ranges. 

in this case it seems that most (almost all) values fall into the first bin (which is white) 

![2017-06-01 14_53_19-program manager](https://cloud.githubusercontent.com/assets/4129778/26680542/1ac119d8-46da-11e7-8325-a29b17ef3d8e.png)

**Comment by sgratzl** [comment]
see #382
