### ISSUE TITLE
all attributes are added twice to the popup in Side panel

### ISSUE THREAD

**Issue by mijar** [Caleydo/taggle#361]
see doubled matrices below, the same is for the rest of the attributes that can't be seen until scrolled
![image](https://cloud.githubusercontent.com/assets/7511570/26204448/14d0cb14-3bdf-11e7-82bb-16a57a635774.png)

**Comment by mstreit** [comment]
in which branch/version? does not happen on http://taggle-daily.caleydoapp.org

**Comment by NMO13** [comment]
And also provide the URL hash so that it can be reproduces quickly.

**Comment by mijar** [comment]
@NMO13 the URL hash does not make sense in this case since it is present in the popup in any setup...
@mstreit I created a workspace setup out of a product to see the latest changes and I just downloaded the latest master after Martin's PR...
Don't know where to exactly find which branch versions I have in my setup :(

**Comment by mstreit** [comment]
'./forEach git status'

**Comment by mijar** [comment]
#######################################
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
on phovea_data_hdf/ execute: git status
#######################################
On branch develop
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working tree clean
on phovea_server/ execute: git status
#######################################
On branch develop
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working tree clean
on taggle/ execute: git status
#######################################
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

**Comment by NMO13** [comment]
I can't reproduce it
![image](https://cloud.githubusercontent.com/assets/3988444/26210135/0e1f3c78-3bef-11e7-94c1-9b8f769f8538.png)

**Comment by mstreit** [comment]
@miroslava.jaresova, the problem could be that you have two taggle/mothertable repos that get indexed (e.g. the renamed taggle repo and the old mothertable repo)

**Comment by sgratzl** [comment]
```
on mothertable/ execute: git status
...
on taggle/ execute: git status
```
