### ISSUE TITLE
Can't distinguish between the attribute panels of different matrices

### ISSUE THREAD

**Issue by mijar** [Caleydo/taggle#362]
I added two different matrices and the panels are not labeled with the name of the matrix now, thus I don't know which panel belongs to which matrix (keep in mind that the order of columns in table view can be changed).
![matrices](https://cloud.githubusercontent.com/assets/7511570/26205324/afce1b4c-3be1-11e7-8d3a-75a5e13ebeb3.PNG)

**Comment by sgratzl** [comment]
see #217

**Comment by bikramkawan** [comment]
![2017-06-09_09-47-37](https://user-images.githubusercontent.com/12292333/26966376-150ba5d2-4cfa-11e7-8f78-9c41a43b4aed.gif)

**Comment by sgratzl** [comment]
does wit work vice versa, too? e.g. when highlighting a filter the column is highlighted?

**Comment by bikramkawan** [comment]
I will fix that also.

**Comment by bikramkawan** [comment]
![2017-06-12_14-50-39](https://user-images.githubusercontent.com/12292333/27034604-9c2812cc-4f7e-11e7-8482-d3b43ea8b0d2.gif)
