### ISSUE TITLE
Encoding for missing values for number, string, and categorical columns

### ISSUE THREAD

**Issue by NMO13** [Caleydo/taggle#378]
Steps to reproduce:

- Add a categorical column
- Stratify it
- Add a numerical column with null values

Expected result:
- The dataset should be correctly visualized

Actual result:
- The visualization shows entries twice; the aggregator column and row number column are not shown

![bug](https://cloud.githubusercontent.com/assets/3988444/26639550/6d8f917c-4625-11e7-988f-da254ba555c7.gif)

**Comment by thinkh** [comment]
Coming from #316 the encoding for number, string, and categorical columns is still missing and causing the issues @NMO13 described.

**Comment by sgratzl** [comment]
see https://github.com/phovea/phovea_vis/pull/61

**Comment by sgratzl** [comment]
re sorting bug: https://github.com/Caleydo/taggle/pull/379

**Comment by thinkh** [comment]
In my tests this issue is solved with PR phovea/phovea_vis#61 and #379.
-> Close
