### ISSUE TITLE
AIDS dataset normalization

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/taggle#381]
I just compared the two matrixes: 
 * N. ppl. living with HIV
 * N. ppl. living with HIV norm. 

I guess the second one is just the normalized version of the first one, i.e. the range of the data is just transformed globally. I'm I wrong?

However, when comparing the two heatmaps they have different patterns: 

![2017-06-01 14_47_35-taggle](https://cloud.githubusercontent.com/assets/4129778/26680438/bf7f75f6-46d9-11e7-9311-dea69b3a4ac0.png)

**Comment by sgratzl** [comment]
alternative possible normalization: normalized by popuplation?

**Comment by mijar** [comment]
It is normalized by population and multiplied with a scalar value then.

**Comment by mijar** [comment]
I changed the names of the columns and the corresponding ranges. Thanks for the suggestions
