### ISSUE TITLE
unify histogram looks between MatrixFilter and NumericFilter

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/taggle#382]
atm the two have very different styles: 

![2017-06-01 14_57_58-program manager](https://cloud.githubusercontent.com/assets/4129778/26680710/bcb4b736-46da-11e7-87fa-cfe23826c9ac.png)

**Comment by NMO13** [comment]
It looks like this now:
![image](https://user-images.githubusercontent.com/3988444/26870235-9c60dae8-4b6f-11e7-8f0d-455bc2272394.png)

I have removed the sliders for matrix histograms, because they make no sense.

**Comment by NMO13** [comment]
Maybe we should center the histograms a bit so that it looks nicer?
