### ISSUE TITLE
should missing values (NaN) be the largest or smallest value?

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/taggle#384]
currently the largest ones. 

see https://github.com/Caleydo/taggle/blob/master/src/SortHandler/SortHandler.ts#L147 and https://github.com/Caleydo/taggle/blob/master/src/SortHandler/SortHandler.ts#L172

**Comment by mstreit** [comment]
As a user, I would expect that NaN values appear at the end of the list. Hence, if I rank with the semantics 'the higher the better', NaN should be the smallest value. The only exception is if the user has p-values, but let's ignore this for now.
