### ISSUE TITLE
Histogram not resizing when containing only one bar

### ISSUE THREAD

**Issue by katush** [Caleydo/taggle#388]
"Histogram" not resizing when containing only one category in aggregated mode and the width of the column is changed.
![image](https://user-images.githubusercontent.com/8986080/26918820-cd2c2a0a-4c33-11e7-9b0e-2cd5ece7d41e.png)

Steps to reproduce
1. Add categorical column
2. Stratify by it
3. Switch to aggregated mode
4. Change the width of the column

After switching back to unaggregated mode and than back to aggregated the width is correct again.
![image](https://user-images.githubusercontent.com/8986080/26918845-efc81ed4-4c33-11e7-869f-7210359f0acc.png)

**Comment by NMO13** [comment]
I'll have a look at it.
