### ISSUE TITLE
Poster screenshot

### ISSUE THREAD

**Issue by katush** [Caleydo/taggle#391]
![image](https://user-images.githubusercontent.com/8986080/26928423-5a71cede-4c56-11e7-8f69-b6d312a97d25.png)

[URL here](http://localhost:8080/#idtype=AIDS_Countries&AIDS_Countries_0=AIDS_Countries_Continent%3BAIDS_Countries_Human%20devel.%20index%3BAIDS_Countries_Ppl%20knowing%20they%20have%20HIV%20(p%2C%202015)%3BAIDS_Countries_Urban%20Pop%20(p)%3BmothertableNNewHivInfections-p%3BAIDS_Countries_Discriminatory%20attitude%20scale%3BlocalData0%3BmothertableNNewHivInfections&colWidths=116%2C106%2C99%2C119%2C132%2C121&AIDS_Years_3=&AIDS_Years_2=AIDS_Years_HAART%20availability%3BAIDS_Years_Decades%3BlocalData6&AIDS_Years_4=&AIDS_Years_5=&AIDS_Years_6=&AIDS_Years_1=AIDS_Years_Decades%3BAIDS_Years_HAART%20availability%3BlocalData1)

I tried to find attributes that would have nice values and thus it would be easy to see what is going on.

Reproduction steps:
1. Add the second **N. new HIV infections** matrix and aggregate by mean.
2. Reorder the columns - **AIDS_Countries first, Discriminatory attitude and Urban population last**, (other things seem to be in order)
3. Filter out **Oceania and South America**
4. Filter out values lover than 24 from **People knowing they have HIV**. Also fiters out NaN values.
5. Re-add the matrix attributes: HAART availability, Decades, AIDS_Years, in this order. There seems to be a bug, so after loading url, they are gone from table view.
6. Change visual encoding of **Urban Population** - unaggregated to **prop. symbol**, aggregated to **boxplot**. 
7. Aggregate everything except **Asia**

Issues:
- Matrix histograms look ugly (mostly just one bar), and so do the values in matrix aggregated to vector. I looked at all the matrices, but the data look similar.
- The null encoding - do we want to show it? If not, it is impossible to filter out just null values.
- Only part of the filter view fits the screenshot.

**Comment by sgratzl** [comment]
* I don't get the `AIDS_Years` on the first matrix
 * a selection in the detail block is missing
 * second matrix -> layout look should different from my point of view
 * maybe stratify the first matrix for showing this feature, too

**Comment by katush** [comment]
@sgratzl 
> `AIDS_Years` on the first matrix 

it is the matrix of new infections per year X per country, all of the matrices are `year X country`. Or do you mean the barplot visualization itself?

> maybe stratify the first matrix for showing this feature, too

It is stratified by continent and than parts are aggregated. If we stratify it lover in the hierarchy, than we will have several groups per country as well. But we can show more Continents.
(I filtered out more values to reduce height)

![image](https://user-images.githubusercontent.com/8986080/26931974-76428e12-4c62-11e7-8d81-473ac3fa3667.png)

**Comment by sgratzl** [comment]
> AIDS_Years on the first matrix
> 
> it is the matrix of new infections per year X per country, all of the matrices are year X country. Or do you mean the barplot visualization itself?

I mean the attribute on top of the first matrix which is clearly increasing linearly without any useful information


> It is stratified by continent and than parts are aggregated.

I meant stratifing the matrix in the other direction e.g., by decades

**Comment by katush** [comment]
@sam it makes sense to have the matrix sorted by years, as it is time series. Moreover, all these attributes are time sequential (decades, availability of treatments) as well, so stratification and sorting by them won't change the visual appearance (unless you set one ascending and other descending, which makes no sense in this case)

**Comment by thinkh** [comment]
Side note: You can create screenshots with the exact same size using [Google Chrome Dev Tools](https://medium.com/@holger.stitz/capture-screenshots-with-exact-size-for-scientific-publications-using-chrome-dev-tools-912e8fccdd80).

**Comment by mijar** [comment]
there is a known problem of having homogeneous matrices whose columns are time stamps - they should be always sorted by the time (imho) and the categories above the matrix are in fact just indicators of some periods...and might help with understanding the data with stratification.
possible solution now - just hide the div via Dev Tools and not include it in the figure, but it will be sorted time-respectively thanks to it...
possible future solution - indicate in the json with data specs that the matrix is a time-series...and then always keep the order
