### ISSUE TITLE
Remove column button is unnecessary when matrix is added

### ISSUE THREAD

**Issue by mijar** [Caleydo/taggle#393]
The circled button is not working, it is possible to remove the matrix only in its upper filter panel. Another question is - is it really necessary to have two identical histograms for one matrix in the side panel?

![removecolumn](https://user-images.githubusercontent.com/7511570/26966098-004dd8e6-4cf9-11e7-9d19-0229b429027e.PNG)

**Comment by NMO13** [comment]
Yes the lower historgram is actually unnecessary, isn't it?
