### ISSUE TITLE
Matrix de-aggregation button inconsistent behavior

### ISSUE THREAD

**Issue by katush** [Caleydo/taggle#398]
There are two toolbars for aggregated matrix - matrix one and vector one. Both contain the button for matrix de-aggregation.
After clicking on the button in matrix toolbar, the matrix is de-aggregated, which is correct behavior.
After clicking on the button in vector toolbar,  de-aggregated matrix is added to the table, but the aggregated vector stays there as well.
![image](https://user-images.githubusercontent.com/8986080/26967592-1e3f5c5c-4cff-11e7-8376-ea2df861b388.png)

![image](https://user-images.githubusercontent.com/8986080/26967669-657d699c-4cff-11e7-932c-47b135e55534.png)

Either remove one of the buttons, or at least make the behavior consistent.

BTW, I think the tool tip should say Aggregate Me/Deaggregate Me or Expand Me, not Aggregated Me

**Comment by bikramkawan** [comment]
Thats true.! That was in initial concept when user one wants to de aggregate the single aggregated vector and add as independent matrix. So I will remove that. Now user can only de aggregate from the matrix de aggregate icon as below.
![2017-06-12_12-09-32](https://user-images.githubusercontent.com/12292333/27029319-118b4a00-4f68-11e7-89ab-a54ae4cb4777.gif)
