### ISSUE TITLE
Change visual encoding of Years in AIDS dataset from bars to labels

### ISSUE THREAD

**Issue by mijar** [Caleydo/taggle#406]
It should be easy to see which year the data relates to (same case as we included the label column in the main direction in the end?), thus the bars should be replaced with labels.

![years](https://user-images.githubusercontent.com/7511570/26980656-0ac10926-4d33-11e7-876f-5c69912c9f2c.PNG)

**Comment by sgratzl** [comment]
![2017-06-13 17_25_14-mothertable - f__w_mothertable - _mothertable_src_styles__taggle-vis scss -](https://user-images.githubusercontent.com/4129778/27090373-53056588-505d-11e7-9240-c2b4b2c8b641.png)
